#!/usr/bin/env bash
# This script displays numbers from 1 to 100, replacing multiples of 3 with "Fizz", multiples of 5 with "Buzz", and multiples of both 3 and 5 with "FizzBuzz"

counter=1
while [ $counter -le 100 ]
do
  if [ $((counter % 3)) -eq 0 ] && [ $((counter % 5)) -eq 0 ]; then
    echo "FizzBuzz"
  elif [ $((counter % 3)) -eq 0 ]; then
    echo "Fizz"
  elif [ $((counter % 5)) -eq 0 ]; then
    echo "Buzz"
  else
    echo "$counter"
  fi
  counter=$((counter+1))
done
