#!/bin/bash
# This script tells a story about users based on /etc/passwd using a while loop.

while IFS=: read -r username _ gid _ home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode x, more info about the user here: $username"
done < /etc/passwd
