#!/usr/bin/env bash

# Backup the hosts file
sudo cp /etc/hosts /etc/hosts.backup

# Change localhost to 127.0.0.2
sudo sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts

# Change facebook.com to 8.8.8.8
sudo sed -i 's/facebook.com/8.8.8.8/' /etc/hosts
